#!/usr/bin/env node
/**
 * Vendor the web fonts into this repository.
 *
 *     node client/scripts/fetch-fonts.mjs
 *
 * The application used to @import them from fonts.googleapis.com on every page
 * load. Three reasons that had to stop:
 *
 *  - nginx already declares `font-src 'self' data:`. It is report-only today,
 *    so the fonts still arrive and the console fills with violations. The day
 *    that policy is enforced — which is the entire point of having it — every
 *    page silently loses its typeface.
 *  - Every page load told Google who uses this system and from which address.
 *    For a product sold partly on "your data never leaves your building", that
 *    is a contradiction sitting in the stylesheet.
 *  - A deployment on a factory LAN with no outbound internet is a reasonable
 *    way to run this, and it rendered in a fallback typeface with no
 *    explanation.
 *
 * Run this again to update the fonts or add a weight. It rewrites
 * src/fonts.css and the files under src/assets/fonts.
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const FONT_DIR = path.join(HERE, '../src/assets/fonts');
const CSS_OUT = path.join(HERE, '../src/fonts.css');

const FAMILIES = 'family=Sora:wght@400;500;600;700'
    + '&family=Public+Sans:wght@300;400;500;600;700'
    + '&family=IBM+Plex+Mono:wght@400;500';

// Only these. Cyrillic and Greek are dead weight for this product, and each
// subset is a separate file the browser may fetch.
const SUBSETS = new Set(['latin', 'latin-ext']);

// A desktop UA, because Google serves woff2 to modern browsers and older
// formats to anything it does not recognise.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
    + '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const main = async () => {
    const res = await fetch(`https://fonts.googleapis.com/css2?${FAMILIES}&display=swap`,
        { headers: { 'User-Agent': UA } });
    if (!res.ok) throw new Error(`Google Fonts returned ${res.status}`);
    const css = await res.text();

    // Each @font-face is preceded by a comment naming its subset.
    const blocks = [...css.matchAll(/\/\*\s*([\w\-[\]]+)\s*\*\/\s*(@font-face\s*\{[^}]+\})/g)];
    if (!blocks.length) throw new Error('No @font-face blocks found — has the CSS format changed?');

    await fs.mkdir(FONT_DIR, { recursive: true });
    for (const f of await fs.readdir(FONT_DIR)) await fs.unlink(path.join(FONT_DIR, f));

    const faces = [];
    for (const [, subset, block] of blocks) {
        if (!SUBSETS.has(subset)) continue;

        const family = /font-family:\s*'([^']+)'/.exec(block)[1];
        const style = /font-style:\s*(\w+)/.exec(block)[1];
        // The whole value, not the first number. Sora and Public Sans are
        // variable fonts and declare a RANGE — "font-weight: 100 800". Reading
        // only the first number named four different files identically, so each
        // download overwrote the last and three weights vanished.
        const weight = /font-weight:\s*([\d\s]+?);/.exec(block)[1].trim();
        const url = /url\((https:\/\/fonts\.gstatic\.com[^)]+)\)/.exec(block)[1];
        const range = /unicode-range:\s*([^;]+);/.exec(block)?.[1];

        // Named from the URL's own filename, which Google already guarantees is
        // unique per file — no invented scheme to collide with itself.
        const name = `${family.replace(/\s+/g, '')}-${subset}-${path.basename(url)}`;

        const file = await fetch(url, { headers: { 'User-Agent': UA } });
        if (!file.ok) throw new Error(`${name}: ${file.status}`);
        await fs.writeFile(path.join(FONT_DIR, name), Buffer.from(await file.arrayBuffer()));

        faces.push({ family, style, weight, name, range });
    }

    const header = `/*
 * Fonts, served from this origin. Generated by scripts/fetch-fonts.mjs — edit
 * that script, not this file.
 *
 * These were loaded from fonts.googleapis.com until 17 August 2026. The CSP
 * declares font-src 'self' data:, every page load reported the user to Google,
 * and an air-gapped install had no typeface at all.
 *
 * ${faces.length} faces, latin and latin-ext only. A browser downloads just the
 * weights and ranges a page actually uses.
 */`;

    const body = faces.map(({ family, style, weight, name, range }) => `@font-face {
    font-family: '${family}';
    font-style: ${style};
    font-weight: ${weight};
    font-display: swap;
    src: url('./assets/fonts/${name}') format('woff2');${range ? `
    unicode-range: ${range};` : ''}
}`).join('\n\n');

    await fs.writeFile(CSS_OUT, `${header}\n\n${body}\n`);

    const bytes = (await Promise.all(
        faces.map(async (f) => (await fs.stat(path.join(FONT_DIR, f.name))).size)
    )).reduce((a, b) => a + b, 0);

    console.log(`${faces.length} faces, ${Math.round(bytes / 1024)} KB, written to src/assets/fonts`);
    console.log(`unique files: ${new Set(faces.map((f) => f.name)).size}`);
};

main().catch((err) => { console.error(err.message); process.exit(1); });
