#!/usr/bin/env bash
#
# Install NeevTime on a clean machine.
#
#   ./install.sh
#
# This script IS the installation procedure. docs/INSTALL.md describes what it
# does and the decisions it cannot make for you; it does not repeat the steps,
# because a procedure written in prose beside a script that performs it will
# disagree with the script within a month. CI runs this file on a fresh runner
# on every push, so the documented install is the tested install.
#
# Safe to re-run. It creates what is missing and leaves what exists alone —
# including .env, which is never overwritten: the secrets in it are the only
# copy, and regenerating them logs every user out and orphans the database.

set -euo pipefail

cd "$(dirname "$0")"

say()  { printf '\n\033[1m%s\033[0m\n' "$1"; }
ok()   { printf '  \033[32m✓\033[0m %s\n' "$1"; }
warn() { printf '  \033[33m!\033[0m %s\n' "$1"; }
die()  { printf '  \033[31m✗\033[0m %s\n' "$1" >&2; exit 1; }

# ── 1. What must already be here ─────────────────────────────────────────────
say "1. Prerequisites"

command -v docker >/dev/null 2>&1 || die "Docker is not installed. See https://docs.docker.com/engine/install/"
docker info >/dev/null 2>&1 || die "The Docker daemon is not reachable. Start Docker and run this again."
docker compose version >/dev/null 2>&1 || die "This needs Docker Compose v2 (the 'docker compose' subcommand)."
ok "Docker $(docker version --format '{{.Server.Version}}') with Compose v2"

# ── 2. Secrets ───────────────────────────────────────────────────────────────
say "2. Secrets"

# Generated, never defaulted.
#
# docker-compose.yml used to fall back to JWT_SECRET=super_secret_key_123 and a
# database password of `admin`, both published in this repository. An install
# that skipped this step was one where anyone holding the source could mint a
# valid administrator token without knowing any password. The compose defaults
# are gone; a missing secret now stops the stack instead of quietly weakening
# it, and this is where they come from.
if [ -f .env ]; then
    ok ".env exists — leaving it untouched"
    for key in JWT_SECRET DB_PASSWORD; do
        grep -q "^${key}=." .env || die ".env exists but ${key} is empty. Set it, or delete .env and re-run."
    done
else
    umask 077   # before the file exists, not after

    # The first administrator's password. install.sh owns it so it is never
    # lost to scrollback: it lands in .env (mode 600), ensureFirstAdmin reads it
    # on first boot, and step 7 prints it. Interactive installs may choose one;
    # a blank answer or a non-interactive run generates a strong one.
    ADMIN_PW=""
    if [ -t 0 ]; then
        printf '  Set the administrator password (leave blank to generate one): '
        read -rs ADMIN_PW; echo
    fi
    [ -z "$ADMIN_PW" ] && ADMIN_PW=$(openssl rand -base64 12 | tr -d '\n=/+' | cut -c1-16)

    {
        echo "# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
        echo "# Keep this file. It is the only copy of these values."
        echo "# Changing JWT_SECRET signs everybody out; changing DB_PASSWORD"
        echo "# without also changing it inside Postgres locks the app out of its"
        echo "# own database."
        echo "JWT_SECRET=$(openssl rand -base64 48 | tr -d '\n=/+' | cut -c1-48)"
        echo "DB_PASSWORD=$(openssl rand -base64 32 | tr -d '\n=/+' | cut -c1-32)"
        echo "DB_USER=postgres"
        echo "DB_NAME=attendance_db"
        echo ""
        echo "# Off-machine backup copy. Point this at a mounted NAS or second"
        echo "# disk, then set /mnt/backup-external in Settings > Database."
        echo "BACKUP_EXTERNAL_DIR=/opt/neevtime-backups"
        echo ""
        echo "# Name on the self-signed certificate. Use the hostname people"
        echo "# will type, or install a real certificate later."
        echo "TLS_COMMON_NAME=neevtime.local"
        echo ""
        echo "# First administrator password, used ONCE on first boot to create"
        echo "# the admin account. Change it after signing in, then this line does"
        echo "# nothing (the account already exists) and can be removed."
        echo "ADMIN_PASSWORD=$ADMIN_PW"
    } > .env
    chmod 600 .env
    ok ".env created with generated secrets (mode 600)"
fi

# ── 3. The database volume ───────────────────────────────────────────────────
say "3. Database volume"

# Created deliberately, exactly once.
#
# The volume is declared `external` in docker-compose.yml so that a MISSING
# volume fails the deploy rather than silently starting a blank database. A
# blank database is indistinguishable from total data loss from the outside,
# and on 16 August 2026 it was reported as exactly that. The cost of that
# safety is this step, on a new install only.
if docker volume inspect neevtime_postgres_data >/dev/null 2>&1; then
    ok "neevtime_postgres_data already exists — an existing database will be used"
else
    docker volume create neevtime_postgres_data >/dev/null
    ok "neevtime_postgres_data created (empty — the schema loads on first boot)"
fi

mkdir -p "$(grep '^BACKUP_EXTERNAL_DIR=' .env | cut -d= -f2- || echo /opt/neevtime-backups)" 2>/dev/null \
    && ok "backup directory ready" \
    || warn "could not create the external backup directory — create it by hand, or backups have nowhere to copy to"

# ── 4. Build and start ───────────────────────────────────────────────────────
say "4. Build and start"

docker compose build client server
docker compose up -d
ok "containers started"

# ── 5. Wait for it to actually work ──────────────────────────────────────────
say "5. Waiting for the application"

# On a first install this includes the database creating itself and loading the
# schema, which is slower than a redeploy. Polling rather than sleeping, because
# a fixed sleep is either too short on a slow machine or wasted on a fast one.
code=""
for i in $(seq 1 90); do
    code=$(curl -skL -o /dev/null -w '%{http_code}' --max-time 3 http://localhost/api/health || true)
    [ "$code" = "200" ] && break
    sleep 2
done
[ "$code" = "200" ] || {
    printf '\n'
    docker compose logs --tail 40
    die "/api/health never answered (last: ${code:-no response}). The log above says why."
}
ok "the application is answering"

# ── 6. Migrations ────────────────────────────────────────────────────────────
say "6. Migrations"

# Applied here, not at boot.
#
# migrations/runner.js is deliberately not wired into startup: a migration can
# empty a table or change who may read one, and an unrelated deploy should never
# carry that into production on its own. So it is applied by the person doing
# the install or the update, which is this script, and ./verify-deploy.sh
# reports anything still pending.
if docker compose exec -T server node migrations/runner.js up; then
    ok "migrations applied"
else
    warn "migrations did not apply — run: docker compose exec server node migrations/runner.js status"
    warn "until they do, the audit trail records nothing"
fi

# ── 7. The first administrator ───────────────────────────────────────────────
say "7. First administrator"

# The password is in .env (this run put it there), so it is retrievable no
# matter how far the boot log has scrolled — the previous version relied on a
# log line that a customer never manages to catch. On a re-run against an
# existing database the admin already exists and ADMIN_PASSWORD does nothing.
ADMIN_PW=$(grep '^ADMIN_PASSWORD=' .env 2>/dev/null | cut -d= -f2-)
if [ -n "$ADMIN_PW" ]; then
    printf '  \033[1m%s\033[0m\n' "Sign in with:"
    echo "    username: admin"
    echo "    password: $ADMIN_PW"
    echo "  (also stored in .env; change it after signing in, then remove that line)"
else
    ok "an administrator already exists — sign in with the password from your first install"
fi

say "Installed"
cat <<'NEXT'
  Open  https://<this machine>/   (the certificate is self-signed; expect a warning)

  Then, in this order:

    1. Settings > Email/SMTP        — alerts and password resets need it
    2. Settings > Database          — set the second copy to /mnt/backup-external
    3. Point the readers at this machine on port 80, path /iclock
       (clear text on purpose: the readers cannot follow a redirect)

  Verify any time with:  ./verify-deploy.sh
NEXT
