-- Remove Absent rows generated for people who have already left.
--
-- The attendance engine scored every employee row regardless of employment
-- status, so seven resigned staff picked up an Absent record for every day in
-- the range — 56 rows in a single week, and growing daily. They inflate absence
-- counts and headcount in every report that reads this table.
--
-- The engine no longer creates these. This clears the ones already written.
--
-- Deliberately narrow. It removes only rows that are:
--   * Absent — never Present, Half Day or anything earned by a real punch
--   * for an employee whose status says they have left
--   * with no punch on that date, so nothing that reflects real attendance
--   * not finalised, so no hand-correction is touched
--
-- Someone who resigned mid-month keeps every real day they worked.
--
--   docker exec -i attendance_db psql -U postgres -d attendance_db \
--     < server/sql/clear_former_employee_absences.sql

BEGIN;

-- Look before deleting. These are the rows that will go.
SELECT s.employee_code, e.status, count(*) AS absent_rows,
       min(s.date) AS from_date, max(s.date) AS to_date
FROM attendance_daily_summary s
JOIN employees e ON e.employee_code = s.employee_code
WHERE s.status = 'Absent'
  AND e.status ~* 'resign|terminat|inactive|left|exit'
  AND s.is_finalized IS NOT TRUE
  AND NOT EXISTS (
      SELECT 1 FROM attendance_logs l
      WHERE l.employee_code = s.employee_code
        AND l.punch_time::date = s.date
  )
GROUP BY 1, 2
ORDER BY 1;

DELETE FROM attendance_daily_summary s
USING employees e
WHERE e.employee_code = s.employee_code
  AND s.status = 'Absent'
  AND e.status ~* 'resign|terminat|inactive|left|exit'
  AND s.is_finalized IS NOT TRUE
  AND NOT EXISTS (
      SELECT 1 FROM attendance_logs l
      WHERE l.employee_code = s.employee_code
        AND l.punch_time::date = s.date
  );

-- Should return no rows.
SELECT s.employee_code, count(*) AS still_absent
FROM attendance_daily_summary s
JOIN employees e ON e.employee_code = s.employee_code
WHERE s.status = 'Absent' AND e.status ~* 'resign|terminat|inactive|left|exit'
GROUP BY 1;

COMMIT;
-- ROLLBACK;  -- if the first list included anyone who should not have been there

-- Note: this is the one script in this set that deletes rows. It is safe
-- because every row it removes was generated by the engine and contains no
-- record of anything that happened — an Absent for a person who had already
-- left, on a day they did not punch. Re-running the recompute would recreate
-- them under the old code and will not under the new.
