/**
 * Categorical colours for the dashboard charts.
 *
 * These were previously generated by rotating hue away from the brand colour,
 * so the charts followed a rebranded palette. That was the wrong trade. Evenly
 * spaced hues at one saturation produce neighbours the eye cannot separate —
 * the ring came out as neon green into yellow into orange — and nothing about a
 * generated sweep guarantees that two adjacent slices are distinguishable to a
 * colourblind reader.
 *
 * This is a fixed, validated order instead. Slices are days and departments:
 * they have no rank and no good or bad, so what they need is to be *told apart*,
 * which is a measurable property rather than a matter of taste. Both columns
 * clear the lightness band, the chroma floor, adjacent-pair separation under
 * simulated protanopia/deuteranopia/tritanopia, and the normal-vision floor,
 * checked against the surfaces these charts actually sit on (white cards in
 * light mode, slate-800 in dark) rather than against generic ones.
 *
 * Three light-mode hues and one dark sit below 3:1 contrast against their
 * surface. That is permitted only with "relief" — the identity must also be
 * carried by something other than colour. DonutCard's legend names every bucket
 * with its count, so it qualifies; a donut without that legend would not.
 *
 * The brand colour still drives everything that is genuinely about identity:
 * the headline cards, buttons, the nav, the ambient background. Chart slices
 * are not branding.
 *
 * Assign in order and never cycle. Beyond eight buckets the answer is to group
 * the tail as "Other", not to invent a ninth hue.
 */

/** Light-mode steps, for a white-ish chart surface. */
export const CATEGORICAL_LIGHT = [
    '#2a78d6', // blue
    '#eb6834', // orange
    '#1baf7a', // aqua
    '#eda100', // yellow
    '#e87ba4', // magenta
    '#008300', // green
    '#4a3aa7', // violet
    '#e34948'  // red
];

/**
 * Dark-mode steps. The same eight hues re-stepped for a dark surface — not the
 * light values dimmed, and not an automatic flip, both of which drift out of
 * the lightness band the separation checks depend on.
 */
export const CATEGORICAL_DARK = [
    '#3987e5',
    '#d95926',
    '#199e70',
    '#c98500',
    '#d55181',
    '#008300',
    '#9085e9',
    '#e66767'
];

/** The palette for the current mode. */
export function categoricalPalette(isDarkMode) {
    return isDarkMode ? CATEGORICAL_DARK : CATEGORICAL_LIGHT;
}

export default categoricalPalette;
